### ISSUE TITLE
Won't build :(

### ISSUE THREAD

**Issue by rborn** [wix/BindingListView#1]
I get this error: `Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/BindingListView.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

I've set  Xcode 'Build Location' to be Relative to Workspace and the path `build/Build/Products` and  `build/Build/Intermediates`

Any idea?  Thank you!

**Comment by silyevsk** [comment]
There was a small issue, fixed in 8ee7c1b .

**Comment by talkol** [comment]
We are using this function from the React Native UIManager but it isn't exported in the h file. I added it manually to my UIManager h file when I did the research and forgot about it :)

`- (void)updateView:(NSNumber *)reactTag viewName:(NSString *)viewName props:(NSDictionary *)props;`

To fix, @silyevsk added an Objective-C category to provide access to this function. Thanks!

**Comment by talkol** [comment]
@rborn please reopen if the build fails again. @silyevsk checked on a computer different than mine and it worked for him now :)

**Comment by rborn** [comment]
It's all ok now, thank you 😸

**Comment by talkol** [comment]
now that you've run it, how is the performance on a real device??

**Comment by rborn** [comment]
@talkol with this question you just unleashed the next "rant" 😆 :

I never liked the listviews in RN, not even the flat one (I know a lot of work is put in it and it suits a certain purpose, but it's just not "native" enough). A listview that doesn't take advantage of the native recycler is not a listview :)

On sim all works fine, trying on device though I get `React/RCTBundleURLProvider.h file not found`
I'll look into it a little later, but I know the performance will be just fine 😉 

I only hope repo this will be pushed forward (my native skills are rusty, but I can help with testing "real world" cases)

**Comment by rborn** [comment]
ok, iPhone 7 with 10.2 works ok, iPhone 5 with 9.3.5 cries about the missing file, the app starts but complains about not finding the server (I changed the ip in the AppDelegate file)

on the iPhone 7 the performance is how it should be 👍

**Comment by rborn** [comment]
@talkol @silyevsk I pulled the last changes you did - https://github.com/wix/BindingListView/commit/85fd9338b9f1c1ada636e3a1c2ebd7118c8ee836- updated `"react-native": "^0.42.3"` and added the `Headers Search Path` as in screenshot and all compiles smooth.
<img width="1000" alt="screen shot 2017-03-21 at 10 45 44" src="https://cloud.githubusercontent.com/assets/406409/24141474/dcc11492-0e23-11e7-84c3-4179fd34f214.png">
Oh, and the performance on my old iPhone 5 is great 👍
